import { useEffect, useState } from 'react'

export const translations = {
  en: {
    languageLabel: 'Language',
    themeLabel: 'Theme',
    english: 'English',
    danish: 'Danish',
    light: 'Light',
    night: 'Night',
    projectTag: 'React + PokeAPI project',
    title: 'Pokedex',
    heroText: 'Explore Pokemon, discover their types, and open each profile for detailed information.',
    aboutProject: 'About project',
    loadingPokemon: 'Loading Pokemon...',
    viewDetails: 'View Details',
    previous: 'Back',
    next: 'Next',
    page: 'Page',
    popularTitle: 'Most Popular Pokemon',
    popularText: 'A spotlight collection of fan-favorite Pokemon that are instantly recognizable from games, cards, and the anime.',
    typeGroupsTitle: 'Pokemon By Type',
    typeGroupsText: 'Types are calculated only from the Pokemon shown on the current page.',
    noTypeMatches: 'No Pokemon of this type on the current page.',
    searchLabel: 'Search current page',
    searchPlaceholder: 'Search by name or type',
    sortLabel: 'Sort',
    sortNumber: 'Number',
    sortName: 'Name',
    sortExperience: 'Base XP',
    sortHeight: 'Height',
    currentPage: 'Current Page',
    pageInsights: 'Page Insights',
    shownPokemon: 'Shown Pokemon',
    availableTypes: 'Available Types',
    topBaseXp: 'Top Base XP',
    tallest: 'Tallest',
    backToList: 'Back to list',
    detailsTag: 'Pokemon details',
    height: 'Height',
    weight: 'Weight',
    baseXp: 'Base XP',
    abilities: 'Abilities',
    backToPokedex: 'Back to Pokedex',
    assignment: 'Assignment 2 - WEB2 Course',
    aboutTitle: 'About Pokedex',
    aboutIntro: 'This application was built to demonstrate React core concepts:',
    fetching: 'Data fetching from PokeAPI',
    routing: 'React Router for navigation',
    styling: 'Responsive cards, custom CSS, theme switching and translations',
    reason: {
      pikachu: 'Mascot of the franchise and one of the most recognized characters in the world.',
      charizard: 'A legendary fan favorite because of its dragon-like design and strong fire attacks.',
      mewtwo: 'Known as one of the strongest and most mysterious legendary Pokemon.',
      eevee: 'Loved for its cute design and many different evolutions.',
    },
    typeNames: {
      fire: 'Fire',
      water: 'Water',
      grass: 'Grass',
      poison: 'Poison',
      electric: 'Electric',
      bug: 'Bug',
      normal: 'Normal',
      flying: 'Flying',
      ground: 'Ground',
      fairy: 'Fairy',
      fighting: 'Fighting',
      psychic: 'Psychic',
      rock: 'Rock',
      ghost: 'Ghost',
      ice: 'Ice',
      dragon: 'Dragon',
      dark: 'Dark',
      steel: 'Steel',
    },
  },
  da: {
    languageLabel: 'Sprog',
    themeLabel: 'Tema',
    english: 'Engelsk',
    danish: 'Dansk',
    light: 'Lyst',
    night: 'Nat',
    projectTag: 'React + PokeAPI projekt',
    title: 'Pokedex',
    heroText: 'Udforsk Pokemon, se deres typer, og åbn hver profil for flere detaljer.',
    aboutProject: 'Om projektet',
    loadingPokemon: 'Indlæser Pokemon...',
    viewDetails: 'Se detaljer',
    previous: 'Tilbage',
    next: 'Næste',
    page: 'Side',
    popularTitle: 'Mest Populære Pokemon',
    popularText: 'En udvalgt samling af fanfavoritter, som er kendt fra spil, kort og anime.',
    typeGroupsTitle: 'Pokemon Efter Type',
    typeGroupsText: 'Typerne beregnes kun ud fra de Pokemon, der vises på den aktuelle side.',
    noTypeMatches: 'Ingen Pokemon af denne type på den aktuelle side.',
    searchLabel: 'Søg på aktuel side',
    searchPlaceholder: 'Søg efter navn eller type',
    sortLabel: 'Sorter',
    sortNumber: 'Nummer',
    sortName: 'Navn',
    sortExperience: 'Base XP',
    sortHeight: 'Højde',
    currentPage: 'Aktuel Side',
    pageInsights: 'Side Indblik',
    shownPokemon: 'Viste Pokemon',
    availableTypes: 'Tilgængelige Typer',
    topBaseXp: 'Højeste Base XP',
    tallest: 'Højeste',
    backToList: 'Tilbage til listen',
    detailsTag: 'Pokemon detaljer',
    height: 'Højde',
    weight: 'Vægt',
    baseXp: 'Base XP',
    abilities: 'Evner',
    backToPokedex: 'Tilbage til Pokedex',
    assignment: 'Opgave 2 - WEB2 kursus',
    aboutTitle: 'Om Pokedex',
    aboutIntro: 'Denne applikation er bygget for at vise centrale React-koncepter:',
    fetching: 'Datahentning fra PokeAPI',
    routing: 'React Router til navigation',
    styling: 'Responsive kort, custom CSS, tema-skift og oversættelser',
    reason: {
      pikachu: 'Franchisens maskot og en af verdens mest genkendelige figurer.',
      charizard: 'En stor fanfavorit på grund af sit dragelignende design og stærke fire-angreb.',
      mewtwo: 'Kendt som en af de stærkeste og mest mystiske legendary Pokemon.',
      eevee: 'Elsket for sit søde design og sine mange forskellige evolutioner.',
    },
    typeNames: {
      fire: 'Ild',
      water: 'Vand',
      grass: 'Græs',
      poison: 'Gift',
      electric: 'Elektrisk',
      bug: 'Insekt',
      normal: 'Normal',
      flying: 'Flyvende',
      ground: 'Jord',
      fairy: 'Fe',
      fighting: 'Kamp',
      psychic: 'Psykisk',
      rock: 'Sten',
      ghost: 'Spøgelse',
      ice: 'Is',
      dragon: 'Drage',
      dark: 'Mørk',
      steel: 'Stål',
    },
  },
}

export function useAppSettings() {
  const [language, setLanguage] = useState(() => localStorage.getItem('pokedex-language') || 'en')
  const [theme, setTheme] = useState('night')

  useEffect(() => {
    localStorage.setItem('pokedex-language', language)
  }, [language])

  useEffect(() => {
    localStorage.setItem('pokedex-theme', theme)
    document.body.dataset.theme = theme
  }, [theme])

  return {
    language,
    setLanguage,
    theme,
    setTheme,
    t: translations[language],
  }
}
